import AppKit
import XCTest

@testable import flash

final class ClipboardMonitorTests: XCTestCase {
  func testNSPasteboardOrgMarkersKeepPayloadsOutOfHistory() {
    let pasteboard = NSPasteboard(name: NSPasteboard.Name("flash-test-\(UUID().uuidString)"))
    defer { pasteboard.releaseGlobally() }

    pasteboard.clearContents()
    pasteboard.setString("copied by the user", forType: .string)
    XCTAssertTrue(ClipboardMonitor.isRecordable(pasteboard.types ?? []))

    for marker in [
      "org.nspasteboard.ConcealedType",
      "org.nspasteboard.TransientType",
      "org.nspasteboard.AutoGeneratedType",
    ] {
      let markerType = NSPasteboard.PasteboardType(marker)
      pasteboard.clearContents()
      pasteboard.declareTypes([.string, markerType], owner: nil)
      pasteboard.setString("secret", forType: .string)
      pasteboard.setData(Data(), forType: markerType)
      XCTAssertFalse(ClipboardMonitor.isRecordable(pasteboard.types ?? []), marker)
    }
  }
}
