[package]
name = "flash-plugin-screenshot"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "flash-plugin-screenshot"
path = "src/main.rs"

[dependencies]
flash_plugin = { path = "../_flash_plugin_rust" }

[profile.plugin-dev]
inherits = "dev"
opt-level = 1
debug = "line-tables-only"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
