[package]
name = "flash-plugin-aiproviders"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "flash-plugin-aiproviders"
path = "src/main.rs"

[dependencies]
flash_plugin = { path = "../_rust_flash_plugin" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
