[package]
name = "flash-plugin-history"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "flash-plugin-history"
path = "src/main.rs"

[dependencies]
flash_plugin = { path = "../_rust_flash_plugin" }
rusqlite = { version = "0.37", features = ["bundled"] }
serde_json = { workspace = true }
tokio = { workspace = true }
