[package]
name = "flash-plugin-media"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "flash-plugin-media"
path = "src/main.rs"

[dependencies]
flash_plugin = { path = "../_rust_flash_plugin" }
objc2 = "0.6"
objc2-foundation = { version = "0.3", default-features = false, features = [
  "std",
  "NSGeometry",
] }
objc2-app-kit = { version = "0.3", default-features = false, features = [
  "std",
  "NSEvent",
  "NSGraphicsContext",
  "objc2-core-graphics",
] }
objc2-core-graphics = { version = "0.3", default-features = false, features = [
  "std",
  "CGEvent",
  "CGEventTypes",
] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
