[package]
name = "flash-plugin-calculator"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "flash-plugin-calculator"
path = "src/main.rs"

[dependencies]
fend-core = "=1.5.8"
flash_plugin = { path = "../_rust_flash_plugin" }
quick-xml = "0.39.4"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
