#!/usr/bin/env bash
set -euo pipefail

# One-shot driver for the flash-vimium-oracle runner.
#
# What this does, in order, each step idempotent:
#   1. Verify signing identity + Firefox are present
#   2. Provision a browser-test Firefox profile template with pinned Vimium-FF
#      and Marionette enabled
#   3. Build + codesign flash-vimium-oracle
#   4. Run it, forwarding any extra args
#
# Usage:
#   ./Scripts/test-integration-browser.sh
#   ./Scripts/test-integration-browser.sh --fixture baseline-synthetic-001
#   ./Scripts/test-integration-browser.sh --jobs 4
#   ./Scripts/test-integration-browser.sh --update-allow-list
#   ./Scripts/test-integration-browser.sh --setup-only

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

SETUP_ONLY=0
RUN_ARGS=()
for arg in "$@"; do
  case "$arg" in
    --setup-only) SETUP_ONLY=1 ;;
    *) RUN_ARGS+=("$arg") ;;
  esac
done

# -- shared constants -----------------------------------------------------
BIN_NAME="flash-vimium-oracle"
APP_NAME="Flash Vimium Oracle"
OUTPUT_DIR="$PROJECT_DIR/build"
STAGING_APP="$OUTPUT_DIR/$APP_NAME.app"
STAGING_BIN="$STAGING_APP/Contents/MacOS/$BIN_NAME"
INSTALL_APP="/Applications/$APP_NAME.app"
INSTALL_BIN="$INSTALL_APP/Contents/MacOS/$BIN_NAME"
SIGN_IDENTITY="Flash Dev"
KEYCHAIN_PATH="$HOME/Library/Keychains/login.keychain-db"
BUNDLE_ID="com.flash.vimium-oracle"

PROFILE_DIR="$HOME/Library/Application Support/Flash/firefox-browser-test-profile"
WORKER_PROFILE_ROOT="$HOME/Library/Application Support/Flash/firefox-browser-test-workers"
EXT_DIR="$PROFILE_DIR/extensions"
FIXTURES_DIR="$PROJECT_DIR/Tests/BrowserSnapshots"

cleanup_test_apps() {
  /usr/bin/pkill -f "$INSTALL_APP/Contents/MacOS/$BIN_NAME" 2>/dev/null || true
  /usr/bin/pkill -f "$WORKER_PROFILE_ROOT" 2>/dev/null || true
}
trap cleanup_test_apps EXIT
trap 'cleanup_test_apps; exit 130' INT TERM

if [[ -n "${FLASH_BROWSER_FIREFOX_APP:-}" ]]; then
  FIREFOX_APP="$FLASH_BROWSER_FIREFOX_APP"
elif [[ -d "/Applications/Firefox.app" ]]; then
  FIREFOX_APP="/Applications/Firefox.app"
else
  FIREFOX_APP="/Applications/Firefox Developer Edition.app"
fi

VIMIUM_XPI_URL="https://addons.mozilla.org/firefox/downloads/file/4717567/vimium_ff-2.4.2.xpi"
VIMIUM_EXT_ID="{d7742d87-e61d-4b78-b8a1-b469842139fa}"
VIMIUM_XPI="$EXT_DIR/$VIMIUM_EXT_ID.xpi"
VIMIUM_SHA256="131e2a67580e7ae9125ab19781159e61409fac47b441fc2782aab76396ead196"

# -- 1. preflight ---------------------------------------------------------
echo "==> Preflight"

if ! security find-identity -v -p codesigning "$KEYCHAIN_PATH" 2>/dev/null |
  grep -q "\"$SIGN_IDENTITY\""; then
  cat <<EOF >&2
ERROR: signing identity "$SIGN_IDENTITY" not found in $KEYCHAIN_PATH.
Run Scripts/install.sh --dev once first — it creates the stable dev
code-signing identity used by every Flash binary.
EOF
  exit 1
fi

if [[ ! -d "$FIREFOX_APP" ]]; then
  cat <<EOF >&2
ERROR: Firefox not found at $FIREFOX_APP.

Install Firefox, or set FLASH_BROWSER_FIREFOX_APP to a Firefox-family
.app path.
EOF
  exit 1
fi

if [[ ! -d "$FIXTURES_DIR/snapshots" ]]; then
  echo "ERROR: browser fixture snapshots directory not found at $FIXTURES_DIR/snapshots" >&2
  exit 1
fi

if ! find "$FIXTURES_DIR/snapshots" -maxdepth 1 -type f -name '*.html' -print -quit |
  grep -q .; then
  echo "ERROR: no browser fixture snapshots found in $FIXTURES_DIR/snapshots" >&2
  exit 1
fi

# -- 2. profile provisioning ---------------------------------------------
echo "==> Provisioning browser profile template at $PROFILE_DIR"
mkdir -p "$EXT_DIR"

if [[ ! -f "$VIMIUM_XPI" ]]; then
  echo "==> Downloading Vimium-FF 2.4.2"
  TMP_VIMIUM="$(mktemp -t vimium-ff.XXXXXX.xpi)"
  trap 'rm -f "$TMP_VIMIUM"' EXIT
  curl -fsSL -o "$TMP_VIMIUM" "$VIMIUM_XPI_URL"
  ACTUAL="$(shasum -a 256 "$TMP_VIMIUM" | awk '{print $1}')"
  if [[ "$ACTUAL" != "$VIMIUM_SHA256" ]]; then
    cat <<EOF >&2
ERROR: Vimium-FF SHA256 mismatch.
  pinned:  $VIMIUM_SHA256
  got:     $ACTUAL
EOF
    exit 1
  fi
  mv "$TMP_VIMIUM" "$VIMIUM_XPI"
  trap - EXIT
else
  ACTUAL="$(shasum -a 256 "$VIMIUM_XPI" | awk '{print $1}')"
  if [[ "$ACTUAL" != "$VIMIUM_SHA256" ]]; then
    echo "ERROR: existing Vimium-FF XPI checksum mismatch at $VIMIUM_XPI" >&2
    exit 1
  fi
fi

cat >"$PROFILE_DIR/user.js" <<'EOF'
// Generated by Scripts/test-integration-browser.sh.

// Load profile-installed extensions and keep them stable.
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.enabledScopes", 15);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.autoUpdateDefault", false);

// Suppress everything that would race fixture page load.
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.aboutwelcome.enabled", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("toolkit.startup.max_resumed_crashes", -1);
user_pref("browser.sessionstore.max_resumed_crashes", -1);

// Marionette automation server. Each worker profile binds a free port and
// the runner reads it from MarionetteActivePort after launch.
user_pref("marionette.enabled", true);
user_pref("marionette.port", 0);

// Keep Firefox's page accessibility tree available to the AX oracle.
// Firefox uses -1 to force-enable accessibility, 0 for platform default,
// and 1 to force-disable it.
user_pref("accessibility.force_disabled", -1);

// Pin window geometry so fiducial calibration is stable run-to-run.
user_pref("browser.window.width", 1280);
user_pref("browser.window.height", 900);
EOF

# -- 3. build + bundle + codesign ----------------------------------------
echo "==> Building $BIN_NAME (release)"
swift build -c release --product "$BIN_NAME"

BIN_PATH="$(swift build -c release --show-bin-path)/$BIN_NAME"
if [[ ! -f "$BIN_PATH" ]]; then
  echo "ERROR: built binary not at expected path: $BIN_PATH" >&2
  exit 1
fi

echo "==> Assembling $APP_NAME.app"
rm -rf "$STAGING_APP"
mkdir -p "$STAGING_APP/Contents/MacOS"
mkdir -p "$STAGING_APP/Contents/Resources"
cp "$BIN_PATH" "$STAGING_BIN"
echo "APPL????" >"$STAGING_APP/Contents/PkgInfo"
cat >"$STAGING_APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleExecutable</key>
    <string>$BIN_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSAccessibilityUsageDescription</key>
    <string>The Flash browser test runner needs Accessibility to walk Firefox's AX tree while comparing Flash hints with Vimium.</string>
</dict>
</plist>
EOF

echo "==> Codesigning $APP_NAME.app with $SIGN_IDENTITY"
codesign --force --deep \
  --sign "$SIGN_IDENTITY" \
  --identifier "$BUNDLE_ID" \
  "$STAGING_APP" >/dev/null
codesign --verify --strict "$STAGING_APP"

echo "==> Installing to $INSTALL_APP"
rm -rf "$INSTALL_APP"
cp -R "$STAGING_APP" "$INSTALL_APP"

codesign --force --deep \
  --sign "$SIGN_IDENTITY" \
  --identifier "$BUNDLE_ID" \
  "$INSTALL_APP" >/dev/null
codesign --verify --strict "$INSTALL_APP"

/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
  -f "$INSTALL_APP" >/dev/null 2>&1 || true

# -- 4. run --------------------------------------------------------------
if [[ $SETUP_ONLY -eq 1 ]]; then
  echo
  echo "==> Setup complete. Installed: $INSTALL_APP"
  exit 0
fi

echo
echo "==> Running $APP_NAME ${RUN_ARGS[*]:-}"
set +e
"$INSTALL_BIN" \
  --fixtures-dir "$FIXTURES_DIR" \
  --browser-app "$FIREFOX_APP" \
  "${RUN_ARGS[@]}"
RC=$?
set -e

if [[ $RC -eq 2 ]] && [[ -t 1 ]]; then
  if command -v pbcopy >/dev/null 2>&1; then
    printf '%s' "$INSTALL_APP" | pbcopy 2>/dev/null &&
      echo "  → app bundle path copied to clipboard"
  fi
  open "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility" \
    >/dev/null 2>&1 || true
fi
exit $RC
