#!/usr/bin/env bash
set -euo pipefail

# Refresh the searchengines plugin's bang table from the live DuckDuckGo set.
# Writes `<trigger> <url-template>` lines that Plugins/searchengines/build.rs
# compiles into the binary's lookup table. Run this to pull the full ~13k
# bang corpus; the committed file is a curated subset.
#
# Requires: curl, jq.

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$PROJECT_DIR/Plugins/searchengines/bangs.tsv"

{
  echo "# DuckDuckGo bangs: <trigger> <url-template>, generated by Scripts/update-ddg-bangs.sh."
  echo "# {{{s}}} is replaced with the percent-encoded query at runtime."
  curl -fsSL https://duckduckgo.com/bang.js |
    jq -r '.[] | select(.t and .u) | [.t, .u] | @tsv'
} >"$DEST"

echo "Wrote $(grep -cv '^#' "$DEST") bangs to $DEST"
