#!/usr/bin/env bash
set -euo pipefail

# One-shot driver for the flash-vimium-oracle runner.
#
# What this does, in order, each step idempotent:
#   1. Verify signing identity + Firefox Developer Edition are present
#   2. Provision the oracle Firefox profile (companion XPI + Vimium-FF
#      XPI + user.js) — overwrites the companion every time so local
#      edits to Resources/oracle-extension/ are always picked up
#   3. Build + codesign flash-vimium-oracle
#   4. Run it, forwarding any extra args
#
# Why Firefox Developer Edition (not Release):
#   The companion extension is unsigned (signing it would require an
#   AMO submission for every code change — too much friction for a
#   test harness). Only Dev Edition and Nightly honour
#   xpinstall.signatures.required=false; release Firefox silently
#   ignores it.
#
# Usage:
#   ./Scripts/vimium-oracle.sh                      # full setup + run all fixtures
#   ./Scripts/vimium-oracle.sh --fixture baseline-synthetic
#   ./Scripts/vimium-oracle.sh --update-allow-list
#   ./Scripts/vimium-oracle.sh --setup-only         # provision + build, don't run

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

SETUP_ONLY=0
RUN_ARGS=()
for arg in "$@"; do
  case "$arg" in
    --setup-only) SETUP_ONLY=1 ;;
    *) RUN_ARGS+=("$arg") ;;
  esac
done

# -- shared constants -----------------------------------------------------
BIN_NAME="flash-vimium-oracle"
OUTPUT_DIR="$PROJECT_DIR/build"
OUTPUT_BIN="$OUTPUT_DIR/$BIN_NAME"
SIGN_IDENTITY="Flash Dev"
KEYCHAIN_PATH="$HOME/Library/Keychains/login.keychain-db"
BUNDLE_ID="com.flash.vimium-oracle"

PROFILE_DIR="$HOME/Library/Application Support/Flash/firefox-oracle-profile"
EXT_DIR="$PROFILE_DIR/extensions"
COMPANION_SRC="$PROJECT_DIR/Resources/oracle-extension"
COMPANION_ID="flash-oracle@flash.local"
COMPANION_XPI="$EXT_DIR/$COMPANION_ID.xpi"
FIREFOX_APP="/Applications/Firefox Developer Edition.app"

# Bump VIMIUM_SHA256 after the first successful download to lock the
# pin; the script will refuse to install anything else once set.
VIMIUM_XPI_URL="https://addons.mozilla.org/firefox/downloads/latest/vimium-ff/addon-554828-latest.xpi"
VIMIUM_EXT_ID="{d7742d87-e61d-4b78-b8a1-b469842139fa}"
VIMIUM_XPI="$EXT_DIR/$VIMIUM_EXT_ID.xpi"
VIMIUM_SHA256=""

# -- 1. preflight ---------------------------------------------------------
echo "==> Preflight"

if ! security find-identity -v -p codesigning "$KEYCHAIN_PATH" 2>/dev/null |
  grep -q "\"$SIGN_IDENTITY\""; then
  cat <<EOF >&2
ERROR: signing identity "$SIGN_IDENTITY" not found in $KEYCHAIN_PATH.
Run Scripts/install.sh once first — it creates the stable dev
code-signing identity used by every Flash binary.
EOF
  exit 1
fi

if [[ ! -d "$FIREFOX_APP" ]]; then
  cat <<EOF >&2
ERROR: Firefox Developer Edition not found at $FIREFOX_APP.

The companion extension is unsigned. Only Dev Edition or Nightly
honour xpinstall.signatures.required=false; release Firefox silently
ignores it.

Install from:
  https://www.mozilla.org/en-US/firefox/developer/
EOF
  exit 1
fi

if [[ ! -d "$COMPANION_SRC" ]]; then
  echo "ERROR: companion extension source not found at $COMPANION_SRC" >&2
  exit 1
fi

# -- 2. profile provisioning ---------------------------------------------
echo "==> Provisioning profile at $PROFILE_DIR"
mkdir -p "$EXT_DIR"

# Always re-zip the companion so edits to content.js / manifest.json
# take effect on the next launch. The XPI basename must match the
# manifest's gecko.id or Firefox refuses to load it.
rm -f "$COMPANION_XPI"
(cd "$COMPANION_SRC" && zip -qr "$COMPANION_XPI" .)

if [[ ! -f "$VIMIUM_XPI" ]]; then
  echo "==> Downloading Vimium-FF (first run)"
  TMP_VIMIUM="$(mktemp -t vimium-ff.XXXXXX.xpi)"
  trap 'rm -f "$TMP_VIMIUM"' EXIT
  curl -fsSL -o "$TMP_VIMIUM" "$VIMIUM_XPI_URL"
  if [[ -n "$VIMIUM_SHA256" ]]; then
    ACTUAL="$(shasum -a 256 "$TMP_VIMIUM" | awk '{print $1}')"
    if [[ "$ACTUAL" != "$VIMIUM_SHA256" ]]; then
      cat <<EOF >&2
ERROR: Vimium-FF SHA256 mismatch.
  pinned:  $VIMIUM_SHA256
  got:     $ACTUAL
Verify the new release manually, then bump VIMIUM_SHA256 in $(basename "$0").
EOF
      exit 1
    fi
  else
    echo "  (no SHA256 pin set; lock it by adding to $(basename "$0"):"
    echo "     VIMIUM_SHA256=\"$(shasum -a 256 "$TMP_VIMIUM" | awk '{print $1}')\")"
  fi
  mv "$TMP_VIMIUM" "$VIMIUM_XPI"
  trap - EXIT
fi

cat >"$PROFILE_DIR/user.js" <<'EOF'
// Generated by Scripts/vimium-oracle.sh.

// Allow the unsigned companion extension (honoured on Dev Edition / Nightly only).
user_pref("xpinstall.signatures.required", false);
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.enabledScopes", 15);

// Pin Vimium-FF to the installed version; auto-update would defeat any SHA256 pin.
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.autoUpdateDefault", false);

// Suppress everything that would race the fixture page load.
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.aboutwelcome.enabled", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("devtools.onboarding.telemetry.logged", true);

// Pin window geometry so fiducial calibration is stable run-to-run.
user_pref("browser.window.width", 1280);
user_pref("browser.window.height", 900);
EOF

# -- 3. build + codesign --------------------------------------------------
echo "==> Building $BIN_NAME (release)"
swift build -c release --product "$BIN_NAME"

BIN_PATH="$(swift build -c release --show-bin-path)/$BIN_NAME"
if [[ ! -f "$BIN_PATH" ]]; then
  echo "ERROR: built binary not at expected path: $BIN_PATH" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"
cp "$BIN_PATH" "$OUTPUT_BIN"

# Same identity + identifier shape as build-firefox-e2e.sh so a single
# TCC Accessibility grant covers both binaries.
echo "==> Codesigning with $SIGN_IDENTITY"
codesign --force \
  --sign "$SIGN_IDENTITY" \
  --identifier "$BUNDLE_ID" \
  "$OUTPUT_BIN" >/dev/null
codesign --verify --strict "$OUTPUT_BIN"

# -- 4. run --------------------------------------------------------------
if [[ $SETUP_ONLY -eq 1 ]]; then
  echo
  echo "==> Setup complete. Binary at: $OUTPUT_BIN"
  exit 0
fi

echo
echo "==> Running $BIN_NAME ${RUN_ARGS[*]:-}"
exec "$OUTPUT_BIN" "${RUN_ARGS[@]}"
