[package]
name = "flash-plugin-system"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "flash-plugin-system"
path = "src/main.rs"

[dependencies]
flash-plugin = { path = "../_flash_plugin_rust" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
